### ISSUE TITLE
Double check Litmus crowdloan reward amount

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-graph#162]
As @Kailai-Wang mentioned in https://github.com/litentry/research-force/issues/90#issuecomment-1040174477, it would be great if our Litmus crowdloan reward amount could be double-checked before the reward distribution happens on Litmus.

As a reference, [this JSON file](https://github.com/litentry/crowdloan-distributor/blob/main/reward_list.json) stores the calculated reward amount of each contributor. The format is like this:
```
[
    [contributorAddress, rewardAmount],
    ...
]
```
where `rewardAmount` is with the unit of 10^-12 LIT.

Please make sure to take the referral also into consideration.

**Comment by geastwood** [comment]
Or @bdmason you can showcase how to get the data directly with the graphql interface by providing the query. 😸

**Comment by h4n0** [comment]
Would be better if any of you can calculate the rewards again and this guarantees calculation or logic errors existing in my code. What do you think?

> Or @bdmason you can showcase how to get the data directly with the graphql interface by providing the query. 😸

**Comment by bdmason** [comment]
Sorry guys I've just seen this, already spoken to @h4n0, I shared the query for the graph on the [original issue](https://github.com/litentry/research-force/issues/90#issuecomment-1061612052), and I'm going to double check all the logic now to make sure everything matches.

**Comment by h4n0** [comment]
The reward result has been verified by @bdmason 's implementation (different implementation, different data source) and proven to be correct.
