### ISSUE TITLE
To create a new bounty additional requirements needs to be provided from the API

### ISSUE THREAD

**Issue by Ekaanth** [litentry/litentry-graph#174]
Currently, we get the details of the existing bounties, while to add a new bounty, we need further information. Please refer to the code that is pointed to and the hook.
required [parameters](https://github.com/polkadot-js/apps/blob/1a490b547d179cea43faff3282f5dbff9329c99d/packages/page-bounties/src/BountyCreate.tsx#L22) and hook:
`const { bountyDepositBase, bountyValueMinimum, dataDepositPerByte, maximumReasonLength, proposeBounty } = useBounties();`

**Comment by franjs** [comment]
Fixed by https://github.com/litentry/litentry-graph/pull/177
