### ISSUE TITLE
Add ETH_MAINNET_PROVIDER as GH action environment variable

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-graph#178]
The `ETH_MAINNET_PROVIDER` has to be present in `.env` file to support some features within litentry-graph.

I would suggest that we set up a GH action environment variable `ETH_MAINNET_PROVIDER="some litentry-org-access-key-url"` to deploy the litentry-graph and for personal testing purpose, one has to get a free tier provider.

**Comment by bdmason** [comment]
The docker build isn't picking it up. @markdavison will look into options, but it looks like we may have to build the container on github then pull it down on the server

**Comment by bdmason** [comment]
@markdavison now we are using docker a lot, there might be a lot of value in a private docker host, as the less going on on the servers the easier they will become to manage. Although I don't know how the much complexity it will introduce with nginx/certbot integration.

**Comment by geastwood** [comment]
@markdavison @bdmason what's the update here?

**Comment by bdmason** [comment]
Closing as this will get superseded by AWS work
