### ISSUE TITLE
Querying kusama fails intermittently 

### ISSUE THREAD

**Issue by markdavison** [litentry/litentry-graph#212]
```
  substrateChainCouncil {
    members {
      address
    }
  }
```

was failing until it was restarted.

As reported here: https://litentry.slack.com/archives/C02C0QH27CY/p1648537988024789

and discussed here:

https://litentry.slack.com/archives/C02C0QH27CY/p1648538798315269

**Comment by geastwood** [comment]
@markdavison is this still relevant?

**Comment by markdavison** [comment]
Yes, it is still an intermittent issue. It is resolved by restarting the connection. We need to spend some time investigating the cause. I suspect we will end up detecting when it errors and restarting the connection.
