### ISSUE TITLE
Data mismatch in squid indexer and polkadot network

### ISSUE THREAD

**Issue by ishrak-imam** [litentry/litentry-graph#228]
![Screenshot 2022-04-25 at 16 15 45](https://user-images.githubusercontent.com/16683923/165107638-5bc42011-0260-4db0-beb7-47e6b3dfd797.png)
![Screenshot 2022-04-25 at 16 15 56](https://user-images.githubusercontent.com/16683923/165107666-bde9b5fb-0d67-43d2-8442-e8535bd5b24d.png)

Polkadot data for open tips and that of indexer don't match.

**Comment by jdomingos** [comment]
@ishrak-imam, it's not an easy fix.
In the latest blocks, there is a tip creating using a multisignature. 
Seems like our indexers and squid cannot read the properly and are returning an error.

I'll keep you posted

**Comment by jdomingos** [comment]
Fix is here: 
https://github.com/litentry/squid/pull/88

It has been validated locally.

**Comment by jdomingos** [comment]
Seems everything is good!
