### ISSUE TITLE
[Web3Go] evm postgres table complement

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-graph#242]
For tables after decode, event/transaction tables currently have signature "MethodName/EventName(****)" info.
We hope the original raw binary info also being included. (Topic0 & MethodId)

**Comment by geastwood** [comment]
I think we have discussed this in the meeting, tks @wangminqi for convert it to an issue.

**Comment by bdmason** [comment]
Moved to the EVM repo here: https://github.com/litentry/evm-processor/issues/52
