### ISSUE TITLE
Index Past Tips

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-graph#254]
We would like to also display the past tips in Kusama and Polkadot.
Data that needs to be indexed:
- Tip Beneficiary
- Tip Finder (the person who suggested the tip)
- Reason
- Status
- Amount of the reward/tip
- List of tippers with value of tip

**Comment by franjs** [comment]
We are already getting the tips data from the indexer. (The past tips are already available in the graph). @stephanie-olp FYI
