### ISSUE TITLE
Research the rule of EVM padding code

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-graph#257]
https://etherscan.io/tx/0x92a0d3e9190cdb9ae986e95a922452bb864835130e7c382265a6c6689d71fa19
The sample shows that in the past version of code, address value can be padded with random value. It may not be limited to address (other fixed length datatype is also potential). We do not know if we manually padding the data, can EVM still recognize.

The decoder needs a rule for handling such type of error. We need some research and test about this topic.

**Comment by geastwood** [comment]
If I understand correctly we currently throw an error in this case. However we want to do research to be able to decode in such case?

**Comment by bdmason** [comment]
this is the wrong repository for issues, this is where we do EVM work https://github.com/litentry/evm-processor

**Comment by geastwood** [comment]
FYI: https://github.com/litentry/evm-processor/issues/102
