### ISSUE TITLE
Include registrars with zero fee

### ISSUE THREAD

**Issue by ishrak-imam** [litentry/litentry-graph#95]
Currently the proxy returns the registrar list excluding the ones having zero fee. All of the registrars should be included regardless of the fee.

File/function to be modified -
`api-gateway/subschemas/substrate-api-proxy/src/resolvers/Query/registrars.ts`

The filter `.filter((r) => !!r?.fee.gt(BN_ZERO))` should be removed

**Comment by franjs** [comment]
@ishrak-imam After including this there is an issue in the app (Registrar 1 is index 2). It should be index 1

![File](https://user-images.githubusercontent.com/8374946/156347284-b33e5cd6-8824-4f10-a5f7-336094d67099.jpg)
